version: '3.5'

services:
  db:
    image: postgres
    container_name: 'spotifi-app-db'
    env_file:
      - ./.env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
    - spotifi_db
  
  app:
    build:             
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: 'spotifi-app'
    command: python manage.py runserver 0.0.0.0:3000
    depends_on:
      - db
    networks:
    - spotifi_db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
  
  # cron:
  #   build:             
  #     context: .
  #     dockerfile: ./.docker/Dockerfile
  #   container_name: 'spotifi-app-cron'
  #   command: cron -f
  #   depends_on:
  #     - db
  #   networks:
  #   - spotifi_db
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - .:/usr/src/app

networks:
  spotifi_db:
    driver: bridge
