# Generated by Django 2.2.25 on 2022-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalplaylist',
            name='title',
            field=models.CharField(default='unknown :p', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalplaylist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
