# Generated by Django 2.2.25 on 2022-05-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='category',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='musics',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Album'),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Playlist'),
        ),
    ]
