# Generated by Django 2.2.25 on 2022-05-04 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220504_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='playlist',
        ),
        migrations.AddField(
            model_name='music',
            name='playlists',
            field=models.ManyToManyField(to='api.Playlist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='unknown music container :p', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(default='unknown music container :p', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='unknown music container :p', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='unknown music container :p', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PersonalPlaylist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Playlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.playlist',),
        ),
    ]
