# Generated by Django 2.2.25 on 2022-05-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220504_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='playlists',
            field=models.ManyToManyField(default=[], to='api.Playlist'),
        ),
    ]
