# Generated by Django 2.2.25 on 2022-05-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220504_1957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musiclike',
            unique_together={('user', 'music')},
        ),
        migrations.AlterUniqueTogether(
            name='musicview',
            unique_together={('user', 'music')},
        ),
    ]
